name: page
on:
  push:
    branches:
      - main
    paths-ignore:
      # - 'README.md'
  workflow_dispatch:

env:
  TZ: Asia/Shanghai

concurrency:
  group: release-ci-group
  cancel-in-progress: false

jobs:
  release-and-page:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package.json') }}

      - name: Install Dependency
        # run: yarn global add tiddlywiki
        run: yarn install

      - name: Build
        run: |
          yarn build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: |
            ./public
